# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import hello_pb2 as hello__pb2


class HelloStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.World = channel.unary_unary(
        '/Hello/World',
        request_serializer=hello__pb2.Name.SerializeToString,
        response_deserializer=hello__pb2.Welcome.FromString,
        )
    self.Person = channel.stream_stream(
        '/Hello/Person',
        request_serializer=hello__pb2.Name.SerializeToString,
        response_deserializer=hello__pb2.Welcome.FromString,
        )


class HelloServicer(object):

  def World(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Person(self, request_iterator, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HelloServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'World': grpc.unary_unary_rpc_method_handler(
          servicer.World,
          request_deserializer=hello__pb2.Name.FromString,
          response_serializer=hello__pb2.Welcome.SerializeToString,
      ),
      'Person': grpc.stream_stream_rpc_method_handler(
          servicer.Person,
          request_deserializer=hello__pb2.Name.FromString,
          response_serializer=hello__pb2.Welcome.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Hello', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
